# -*- coding: utf-8 -*-
"""18097.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hlZIGcYDiuQ8b7WkjxCevVxJkfJVJrxc
"""

!wget https://raw.githubusercontent.com/Dinesh-Adhithya-H/Applied-machine-learning/master/dsml_ass2_tree_dataset.csv

import pandas as pd
import seaborn as sns
import sklearn as sk
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv("/content/dsml_ass2_tree_dataset.csv",header=None,delimiter=",")

data



y=np.array(data[6])
x=np.array(data.drop([6],axis=1))

x.shape,y.shape

x[0]

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

x_train,x_test,y_train,y_test=train_test_split(x,y)

dtc=DecisionTreeClassifier(criterion='entropy').fit(x_train,y_train)

dtc.feature_importances_

from sklearn import tree
plt.figure(figsize=(100,100))
tree.plot_tree(dtc,filled=True)
plt.show()

